### PR TITLE
Add support to other markup languages using pandoc 

### PR DESCRIPTION
**Pull request by larrasket**
It would be nice if one can use their old markup files when migrating to xlog without the need to convert them to markdown, and also preserve them, so it's easier to roll back.

Please add [pandoc](https://archlinux.org/packages/community/x86_64/pandoc/) as an optional dependency to the AUR package if this PL is to be merged. 

Congratulations on this fine piece of software, Emad.

### CODE REVIEW

**Comment by emad-elsaid** [comment]
Hey @salehmu thanks for taking the time to write this solution, I would like to think out loud about this feature: 

# The Feature

- So we need the author to Edit and View documents other than Markdown 
- Some formats are: org, rst, rtf, odt

# Some constraints

- Xlog doesn't add any requirements on the environment if the user downloaded the release binary
- Only Go is required if the user is building from source. 
- I would like to keep this. Xlog is built for many environments, although I only use Linux but I would like breaking this advantage to be the last resort.

# Some details

- Viewing the page means rendering it from the source format to HTML 
- Editing the page means the JS editor should also support this format
- Extensions assume that it's dealing with Markdown 

# Ways to implement this

# an extension
- one way to do this is an extension that defines handlers for paths that ends with specific extension (for viewing) for example: `/{page}.org` 
- an editor page to edit the format for example `/edit/{page}.org`  
- register these pages using `RegisterBuildPage` to build then in the build step
- this extension can implement the Page interface and maybe convert the org format for example to markdown then call all preprocessors (this mean the core should expose `preprocess` function to be public.

## advantages
- this means we can have one extension for each format 

## disadvantage
- the core doesn't know about this format so `EachPage` for example won't include the Org pages in it (maybe that part we can improve to make it extensible)

# Add the support to the Core itself
- This can be done in two ways

- The core converts all formats to one format (markdown or something else like common AST or something)
- The core selects renderer and preprocessors based on the format

## advantages

- The new format is part of the core so all extensions and public API will change to reflect that for the extensions

## disadvantages

- extensions has to be aware of multiple formats or use the common format. if we choose Markdown for example we don't need to change existing extensions.
- the core will be larger


# Some general thoughts

- Using Markdown as the Core language and everything translates to it will remove other formats from extra features that are not present in Markdown. probably we should use HTML? and  let extensions work on the HTML instead of extending the Markdown parser?
- Adding a system dependency is my last resort I really prefer not to and maybe using a Go package for the format we're trying to support. 
- We don't have to support 4 new formats at the same time. lets thing about adding one more format beside Markdown and see how this goes.

# So the solution we have in this PR 

- I see it tried to use Markdown as the base language so it converts other language to Markdown and pass it down to the rest of the program like the preprocessors...etc. That's mean we choose here to extend the core. lets talk more about this decision.
- It tries to support 4 new formats at the same time. lets start small for now and focus on one more format.
- It exec Pandoc which means it invokes the program each time we read the file content  
- I would like to add the support without invoking external binary
- I would like to think more about whether we extend the core or go for an extension. if so what should the core offer to allow an extension to do that?

**Comment by salehmu** [comment]
Thanks for sharing your profound thought.

> Using Markdown as the Core language and everything translates to it will remove other
> formats from extra features that are not present in Markdown. probably we should use HTML?
> and let extensions work on the HTML instead of extending the Markdown parser?

I think markdown is the right tool to convert to (keep in mind that I&rsquo;m trying to keep the
nice just-works situation of xlog, I don&rsquo;t wish to involve restructuring of how the program
already works). Pandoc is capable of translating almost every feature form, different formats
in a handy way; some features that aren&rsquo;t widely used might cause some small issues (for
example, `#+begin_verse` block in org-mode is not fully supported with Pandoc and renders to
non-line breaking paragraph; however, If the user manually added line breaks `\\` —which is
what is commonly used— instead of `#+begin_verse` block, it renders fine). Pandoc is even
capable of preserving coloring in some formats, be rendering to HTML blocks inside the
markdown output.

> Adding a system dependency is my last resort I really prefer not to and maybe using a Go
> package for the format we&rsquo;re trying to support.

We will have to write our owns (there is other painful approach that came to my mind, since
there are already Go packages to parse almost every markup language to HTML, so we can
reparse it again to Markdown —from HTML— using [html-to-markdown](https://pkg.go.dev/github.com/JohannesKaufmann/html-to-markdown)). It&rsquo;s somehow possible to
vendor Pandoc (mentioned later).

> I see it tried to use Markdown as the base language so it converts other language to
> Markdown and pass it down to the rest of the program like the preprocessors&#x2026;etc. That&rsquo;s
> mean we choose here to extend the core. lets talk more about this decision.

I tried first to have an interface for rendering instead using Pandoc and then invoke the
interface implementation respecting the file format, this would require to have some logic
for the extensions to register the format type that it is expecting before registering
itself. However:

-   This will mean we have to rewrite many extensions to work with the other format(s) (as you
    mentioned). Subsequently, every new extension would have more than one variant to support
    multiple formats.
-   It will require some logic to handle the available extensions for the user, depending on
    which format they are editing.

Thus supporting other languages would mean much of non-worthwhile work, converting the
languages to a global language (adding support to the core itself) and then apply
already-developed extensions are more applicable IMO.

> It tries to support 4 new formats at the same time. lets start small for now and focus on
> one more format.

It will make no difference if we are going to use Pandoc, it has a standard method of
conversion that is processed in all the [supported formats](https://pandoc.org/MANUAL.html#general-options); the 4 ones that I committed are
actually only the ones that I tested myself, but we can have support for `.docxs` for
example (maybe this would be useful at some point).

> -   It exec Pandoc which means it invokes the program each time we read the file content

That&rsquo;s right, I think we can have a temporary disposable markdown version of
the file instead. What do you think?

> -   I would like to add the support without invoking external binary

I don&rsquo;t see a problem in adding an optional dependency that gives a new flexible feature,
so using this with Pandoc is totally optional for the user (it won&rsquo;t break if they
didn&rsquo;t). However, an option would be to vendor Pandoc binary (which is statically linked,
thus no dynamic dependencies). This adds +16MB to xlog. The current situation for anyone to use
xlog from any other format would involve using an external software anyway to do the work
(probably Pandoc in this case), we will be just cutting the middle man.

Other option would be to use our converter in go rather than Pandoc, reinventing the
bicycle. I don&rsquo;t prefer this approach because it also implies much useless work to do and
there is already a right tool for doing so for us.

---

I think the extension solution is possible, but:

> convert the org format for example to markdown

We will go back to the same problem, how this conversion should be done?

**Comment by emad-elsaid** [comment]
The more I think about it the more I feel it's extending xlog in a way that can cause inconsistency and adds complexity. 

Lets look into how we can support other formats through extensions that way we contain the change in one place. lets look into what's possible and what needs the core package to change. 

1. Change in the edit handler to convert input content to markdown then write it to the Page. 
2. Added functions to `helpers.go` are not registered as template helpers so these can be anywhere
3. Changes to `page` struct to return correct file name and return the content in markdown.

The main issue is 1 and 3. 

1. I think the user should edit his page in the format he prefer if we decided to support that format. switching to markdown in the editor defy the idea. If it's actually a good step then a simple converter from any format to markdown for xlog would be sufficient. So supporting the format should mean to the user view + edit in this format. This can be done with an editor for that format. or even just a simple textarea if it's too much to introduce an editor (actually the markdown editor in xlog made this repo 90% JS). I'm ok with Not introducing the edit functionality at all instead or converting to markdown for the user to edit then convert back to the format to save. but lets say we want to have an editor this is possible by introducing a handler `Get('/\+/edit/{page:*.}.org` which renders the editor and submitting to `Post('/\+/edit/{page:*.}.org` to write the content to a file.
3. a new struct that implement the same Page interface can be used in a new handler `Get('/\+/{page:.*}.org)` to render the page (althought without preprocessing. this will allow rendering the new format to html. without converting it to markdown. if we want to allow preprocessing we'll have to convert to markdown first then passing it to the preprocessors (that will require changing `preProcess` to be renamed to `PreProcess`. I'm also fine with not having to preprocess the page. 

Allowing these new pages to be part of `EachPage` require some kind or registration similar to `RegisterBuildPage`

**Comment by emad-elsaid** [comment]
Another way to build this is to have a new concept `Translators` which : 
1. RegisterExtension : to register and extension translator from whatever this file format to markdown and vise versa
2. struct uses these translators 

this seems cleaner

**Comment by salehmu** [comment]
> so supporting the format should mean to the user view + edit in this format. this can be
> done with an editor for that format. or even just a simple textarea if it&rsquo;s too much to
> introduce an editor (actually the markdown editor in xlog made this repo 90% js).

I think this could be a nice option, how about adding this as a configurable option for
users? So they can use a basic textarea or a converted-to-markdown editor. I&rsquo;d like to
remention that I didn&rsquo;t think of xlog to support other format (it sounds like much job) the
but I liked to migrate easily to it and preserve the original extention for my markup files;
my guess is more people would have the same case (that&rsquo;s why I suggest adding that option to
use it both ways, up to the user to decide).

Regarding the rendering method; I&rsquo;m thinking of implementing that using html as a mediator,
so, the editor course would be, in the case of using a markdown editor, to `.org` (or other,
but as you suggested let&rsquo;s start with org-mode), it will go `.org → .html → .md`, save &
write: `.md → .html .org` (I chose this over trying to convert markdown to org directly
that, 1. I&rsquo;m not sure of how much worth would it be to develop such a scenario. 2.
converting to html sounds more promising for supporting other extensions in the future) and
obviously no need for transmutations if the minimal editor (textarea) is enabled. What do
you think?

**Comment by emad-elsaid** [comment]
I added a commit to introduce the idea of multiple pages source. this can open the door for this feature to be introduced by an extension. I still didn't validate it, will try to take some code from the PR and implement `PageSource` interface.
if this works this feature can be an extension that `RegisterPageSource` and return pages which represent the .org files or any other type. and it'll be just like any other `Page` in the system, extensions can deal with these pages too like markdown files

**Comment by emad-elsaid** [comment]
@larrasket maybe it's a bit late, but I didn't like any of the integration ideas and it took a bit of time to come up with a more generic solution.

so this branch: https://github.com/emad-elsaid/xlog/tree/introduce-pages-source

* now has an extension that defines another source for pages.
* and defines another implementation of page
* xlog goes over all pages sources giving priority to extensions pages sources and if nothing provides the page it reads it from CWD
* the pandoc extension provides a page that can represent a file in the list of SUPPORTED_EXTENSIONS
* and it uses part of your code to render it's content to HTML (fragment)
* so now when you go to `locahost:3000/page-name` if `page-name.org` exists in your directory it will be rendered

can you give it a try and see if it works as expected? 

* it doesn't support other page operations like editing/deleting

**Comment by larrasket** [comment]
@emad-elsaid It works fine (tested with .org & .rst) with me; footnotes and everything is fine as well. I've noticed though that the rename option when used it automatically renames the extension to md (for example renaming `x.org` to y becomes `y.md`) which messes up the formatting totally.

I didn't read the code changes yet, but why does not it support editing/deleting? Both sounds intuitive and easy to implement since it already loads a fine editor. (I remember your assertion on that, but I still believe that basic editing will be better than nothing). 

If you wish, you can download this [example file](https://writequit.org/denver-emacs/presentations/files/example.org) which makes use of all org-mode syntax to test it.

**Comment by emad-elsaid** [comment]
* the rename tool and other places in other extensions assumed the filetype is .md this is why the rename tool is not working correctly 
* I'm still implementing the interface, that was the bare minimum before I invest more time
* thanks for the example org file

**Comment by emad-elsaid** [comment]
- I have fixed the rename function, and allowed editing and deleting. 
- the thing is that other sources probably will never equal the markdown, for example the AST function in the page is expected to return the AST tree and all extensions uses it to extract data and parse additional syntaxt like hashtags. and mentions of other pages in the page. 
- give it a shot in your day-to-day usage and let me know. I don't use any of these formats so I can't spot issues in the implementation

**Comment by larrasket** [comment]
Sure! Going to try it for the next couple of days and I will report here if something is unusual.

**Comment by emad-elsaid** [comment]
I added a flag `-pandoc` (false by default). and merge the branch to master and released a new version 0.80.

**Pull request closed without merging**
